<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BatchRenamer.Core\BatchRenamer.Core.csproj" />
    <ProjectReference Include="..\..\src\BatchRenamer.FileSystem\BatchRenamer.FileSystem.csproj" />
    <ProjectReference Include="..\..\src\BatchRenamer.Transaction\BatchRenamer.Transaction.csproj" />
  </ItemGroup>
</Project>
